<?php

namespace app\components;
use yii\base\Widget;
use yii\helpers\Html;

class Hello extends Widget
{
    public $message;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $emTag = Html::tag('em', HTML::encode($this->message));
        $pTag = Html::tag('p', $emTag);

        return $pTag;
    }

}