<?php

namespace app\components\my_widgets;
use yii\base\Widget;
use yii\helpers\Html;

class Author extends Widget
{
    public $author;
    public $message;
    public $className;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->setClassName(__CLASS__);

        $h3Author = Html::tag('h3', Html::encode($this->author));
        $aMessage = Html::tag('p', Html::encode($this->message . " - Current widget is: \"" . $this->getClassName() . "\""));
        $aLink = Html::a('About author', ['blog/author'], ['class' => 'btn btn-primary']);
        $p_aLink = Html::tag('p', $aLink);
        $div_caption = Html::tag('div', $h3Author.$aMessage.$p_aLink, ['class' => 'caption']);
        $imgAuthor = Html::img('@web/images/widgets/author_roma.jpg', ['alt' => 'My logo']);
        $divThumbnail =Html::tag('div', $imgAuthor.$div_caption, ['class' => 'thumbnail']);
        $divThumbnailParent = Html::tag('div', $divThumbnail, ['class' => 'col-md-12']);
        $divThumbnailRow =Html::tag('div', $divThumbnailParent, ['class' => 'row']);

        return $divThumbnailRow;
    }

    function setClassName($class_path){
        $exploded_class_path = explode('\\', $class_path);
        $this->className = $exploded_class_path[count($exploded_class_path) - 1];
    }

    function getClassName(){
        return $this->className;
    }

}