<?php

namespace app\components\my_widgets;

use Yii;
use app\models\Posts;
use yii\base\Widget;
use yii\helpers\Html;

class RandomPosts extends Widget
{
    public $id;
    public $label;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $posts = Posts::find()->where(['hide' => 0])->limit(4)->where(['not', ['id' => $this->id]])->orderBy("rand()")->all();

        $list_group_item = '';
        foreach ($posts as $post) {
            $h4_heading = Html::tag('h4', $post->title, ['class' => 'list-group-item-heading']);
            $post->link = $post->link . "?all=". Yii::$app->request->get('all');
            $imgPost = Html::img("{$post->img}", ['alt' => $this->getAlt($post->img), 'width' => '100%']);
            $pDate = Html::tag('p', $post->date, ['class' => 'list-group-item-text']);
            $list_group_item .= Html::tag('a', $h4_heading . $imgPost . $pDate, ['href' => $post->link, 'class' => 'list-group-item']);
        }

        $div_list_group = Html::tag('div', $list_group_item, ['class' => 'list-group']);

        return $div_list_group;
    }

    function getAlt($path){
        $exploded_path = explode('/', $path);
        $alt = explode(".", $exploded_path[count($exploded_path) - 1]);

        return $alt[0];
    }

}