<?php

namespace app\components\my_widgets;
use yii\base\Widget;
use yii\helpers\Html;

class SidebarLeft extends Widget
{
    public $author;
    public $message;
    public $className;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->setClassName(__CLASS__);

        $aOnClick = '<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>';
        $aAbout =  Html::a('About author', ['blog/author']);
        $aVideos =  Html::a('Videos', ['blog/videos']);
        $aReviews =  Html::a('Reviews', ['blog/reviews']);
        $aSites =  Html::a('Sites', ['blog/sites']);
        $div_mySidenav = Html::tag('div', $aOnClick.$aAbout.$aVideos.$aReviews.$aSites, ['class' => 'sidenav', 'id' => 'mySidenav']);

        return $div_mySidenav;
    }

    function setClassName($class_path){
        $exploded_class_path = explode('\\', $class_path);
        $this->className = $exploded_class_path[count($exploded_class_path) - 1];
    }

    function getClassName(){
        return $this->className;
    }

}