<?php

namespace app\components\my_widgets;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;

class Socials extends Widget
{
    public $blog_view;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->setClassName(__CLASS__);

        $this->blog_view = Yii::$app->urlManager->createUrl(["blog/{$this->blog_view}"]);

        $vk_like_div = Html::tag('div', '', [ 'id' => 'vk_like', 'class' => 'text-center']);
        $vk_script = Html::tag('script', 'VK.Widgets.Like(\'vk_like\');', ['type' => 'text/javascript']);
        $hr = Html::tag('hr');
        $fb_div = Html::tag('div', '', ['class' => 'fb-like pull-left',
                                        'data-href' => "$this->blog_view",
                                        'data-width' => '300px',
                                        'data-layout' => 'standard',
                                        'data-action' => 'like',
                                        'data-show-faces' => 'true',
                                        'data-share' => 'false',
        ]);

        $returning_content = $vk_like_div . $vk_script. $hr . $fb_div;

        return $returning_content;
    }

    function setClassName($class_path){
        $exploded_class_path = explode('\\', $class_path);
        $this->className = $exploded_class_path[count($exploded_class_path) - 1];
    }

    function getClassName(){
        return $this->className;
    }

}