<?php

namespace app\models;

use yii\db\ActiveRecord;


class Courses extends ActiveRecord
{
    public $img;
    public $order;
    public $link;

    public static function tableName()
    {
//        return 'post'; // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->img = '/web/image/courses/' . $this->alias . '.png';
        $this->order = 'http://localhost/04_test_files/Yes_it_is/web/order?product_ids=' . $this->src_id;
        $this->link = 'http://localhost/04_test_files/Yes_it_is/web/' . $this->src_id;
    }
}