<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;


class Courses extends ActiveRecord
{
    public $img;
    public $order;
    public $link;

    public static function tableName(){
        return 'bl_courses'; // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->img = Yii::$app->homeUrl . 'images/courses/' . $this->alias;
        $this->order = Yii::$app->urlManager->createUrl(['order/index', 'product_ids' => $this->src_id]) ;
        $this->link = 'http://localhost/04_test_files/Yes_it_is/web/' . $this->src_id;
    }
}