<?php

namespace app\models;

use yii\db\ActiveRecord;


class Minicourses extends ActiveRecord
{
    public static function tableName()
    {
//        return 'post'; // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->img = '/web/image/minicourses/' . $this->img;
    }
}
