<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;


class Posts extends ActiveRecord
{
    public $number;

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

//        $this->date = ''; // TODO: Change the date to proper view

        $this->intro_text = $this->replaceContent($this->intro_text);
        $this->full_text = $this->replaceContent($this->full_text);

        $this->img = "/web/images/posts/" . $this->img;
        $this->link = Yii::$app->urlManager->createUrl(["site/post", "id" => $this->id]);
    }

    public function replaceContent($text){
        $this->youtube($text);
//        $this->flowplayer($text);
        return $text;
    }

    private function youtube($text){
        if(strpos($text, "youtube") === false){
            return $text;
        }
        $reg = '/{youtube: ([\w-_]*)?, (\d*)?, (\d*)?/i';
        $text = preg_replace($reg, str_replace(array("%name%, %width%, %height%"), array("\\1", "\\2", "\\3"), file_get_contents(Yii::$app->basePath.Yii::$app->params["dir_tmpl"]."youtube.tpl")), $text);
        return $text;
    }

//    private function flowplayer($text){
//        if(strpos($text, "flowplayer") === false){
//            return $text;
//        }
//        $reg = '/{flowplayer: ([\w-_]*)?, (\d*)?, (\d*)?/i';
//        $text = preg_replace($reg, str_replace(array("%name%, %width%, %height%"), array("\\1", "\\2", "\\3"), file_get_contents(Yii::$app->basePath.Yii::$app->params["dir_tmpl"]."flowplayer.tpl")), $text);
//        return $text;
//    }

    public static function setNumbers($posts){
        $all_releases = Posts::find()->where(['is_release' => 1])->orderBy("date")->all();
        $number = 1;
        foreach ($all_releases as $release){
            foreach ($posts as $post) {
                if($post->id == $release->id){
                    $post->number = $number;
                }
                $number++;
            }
        }
    }

}