<?php

namespace app\models;

use yii\db\ActiveRecord;

class SearchForm extends ActiveRecord
{
    public $q;

    public static function tableName(){
//        return 'bl_posts'; // TODO: Change the autogenerated stub
    }

    public function rules(){
        return [
            ['q', 'string']
        ];
    }
}