<?php

namespace app\models;

use yii\db\ActiveRecord;


class Sef extends ActiveRecord
{
    public static function tableName()
    {
//        return 'post'; // TODO: Change the autogenerated stub
    }
}